export const products = [
    {
        id: "1",
        name: "Wireless Headphones",
        price: 99.99,
        description: "High-quality wireless headphones with noise cancellation.",
        category: "Electronics",
        image: "https://picsum.photos/200?random=1",
        stock: 15,
    },
    {
        id: "2",
        name: "Smartphone Case",
        price: 19.99,
        description: "Durable and stylish smartphone case with shock protection.",
        category: "Accessories",
        image: "https://picsum.photos/200?random=2",
        stock: 50,
    },
    {
        id: "3",
        name: "Gaming Mouse",
        price: 49.99,
        description: "Ergonomic gaming mouse with customizable buttons.",
        category: "Electronics",
        image: "https://picsum.photos/200?random=3",
        stock: 25,
    },
    {
        id: "4",
        name: "Mechanical Keyboard",
        price: 79.99,
        description: "RGB backlit mechanical keyboard for gaming and productivity.",
        category: "Electronics",
        image: "https://picsum.photos/200?random=4",
        stock: 30,
    },
    {
        id: "5",
        name: "4K Monitor",
        price: 299.99,
        description: "Ultra HD 4K monitor with high refresh rate.",
        category: "Electronics",
        image: "https://picsum.photos/200?random=5",
        stock: 10,
    },
    {
        id: "6",
        name: "Bluetooth Speaker",
        price: 59.99,
        description: "Portable Bluetooth speaker with deep bass.",
        category: "Electronics",
        image: "https://picsum.photos/200?random=6",
        stock: 20,
    },
    {
        id: "7",
        name: "Smartwatch",
        price: 149.99,
        description: "Fitness smartwatch with heart rate monitoring.",
        category: "Wearables",
        image: "https://picsum.photos/200?random=7",
        stock: 12,
    },
    {
        id: "8",
        name: "VR Headset",
        price: 199.99,
        description: "Immersive virtual reality headset with adjustable straps.",
        category: "Electronics",
        image: "https://picsum.photos/200?random=8",
        stock: 8,
    },
    {
        id: "9",
        name: "External Hard Drive",
        price: 89.99,
        description: "1TB external hard drive with fast data transfer speeds.",
        category: "Storage",
        image: "https://picsum.photos/200?random=9",
        stock: 40,
    },
    {
        id: "10",
        name: "USB-C Hub",
        price: 34.99,
        description: "Multiport USB-C hub with HDMI, USB, and SD card slots.",
        category: "Accessories",
        image: "https://picsum.photos/200?random=10",
        stock: 22,
    },
    {
        id: "11",
        name: "Wireless Charger",
        price: 29.99,
        description: "Fast wireless charging pad for smartphones and wearables.",
        category: "Accessories",
        image: "https://picsum.photos/200?random=11",
        stock: 35,
    },
    {
        id: "12",
        name: "Laptop Stand",
        price: 45.99,
        description: "Ergonomic aluminum laptop stand for better posture.",
        category: "Accessories",
        image: "https://picsum.photos/200?random=12",
        stock: 18,
    },
    {
        id: "13",
        name: "Smart TV",
        price: 499.99,
        description: "55-inch 4K Smart TV with built-in streaming apps.",
        category: "Electronics",
        image: "https://picsum.photos/200?random=13",
        stock: 5,
    },
    {
        id: "14",
        name: "Portable Power Bank",
        price: 24.99,
        description: "10,000mAh power bank with fast charging capability.",
        category: "Accessories",
        image: "https://picsum.photos/200?random=14",
        stock: 27,
    },
    {
        id: "15",
        name: "Fitness Tracker",
        price: 59.99,
        description: "Activity tracker with sleep monitoring and step counter.",
        category: "Wearables",
        image: "https://picsum.photos/200?random=15",
        stock: 14,
    },
    {
        id: "16",
        name: "Smart Light Bulbs",
        price: 39.99,
        description: "WiFi-enabled smart light bulbs with voice control.",
        category: "Smart Home",
        image: "https://picsum.photos/200?random=16",
        stock: 33,
    },
    {
        id: "17",
        name: "Noise Cancelling Earbuds",
        price: 129.99,
        description: "Wireless earbuds with active noise cancellation.",
        category: "Wearables",
        image: "https://picsum.photos/200?random=17",
        stock: 19,
    },
    {
        id: "18",
        name: "Security Camera",
        price: 89.99,
        description: "1080p security camera with night vision and motion detection.",
        category: "Smart Home",
        image: "https://picsum.photos/200?random=18",
        stock: 15,
    },
    {
        id: "19",
        name: "Tablet",
        price: 299.99,
        description: "10-inch tablet with stylus support and high-resolution display.",
        category: "Electronics",
        image: "https://picsum.photos/200?random=19",
        stock: 11,
    },
    {
        id: "20",
        name: "Electric Toothbrush",
        price: 49.99,
        description: "Rechargeable electric toothbrush with multiple cleaning modes.",
        category: "Personal Care",
        image: "https://picsum.photos/200?random=20",
        stock: 28,
    },
    {
        id: "21",
        name: "Gaming Chair",
        price: 199.99,
        description: "Ergonomic gaming chair with lumbar support and adjustable armrests.",
        category: "Furniture",
        image: "https://picsum.photos/200?random=21",
        stock: 9,
    },
    {
        id: "22",
        name: "Desk Lamp",
        price: 29.99,
        description: "LED desk lamp with adjustable brightness and color temperature.",
        category: "Furniture",
        image: "https://picsum.photos/200?random=22",
        stock: 25,
    },
    {
        id: "23",
        name: "Robot Vacuum",
        price: 249.99,
        description: "Smart robot vacuum with app control and scheduling.",
        category: "Smart Home",
        image: "https://picsum.photos/200?random=23",
        stock: 7,
    },
    {
        id: "24",
        name: "Wireless Keyboard",
        price: 69.99,
        description: "Compact wireless keyboard with rechargeable battery.",
        category: "Electronics",
        image: "https://picsum.photos/200?random=24",
        stock: 16,
    },
    {
        id: "25",
        name: "Portable Air Purifier",
        price: 59.99,
        description: "HEPA filter air purifier for small spaces.",
        category: "Smart Home",
        image: "https://picsum.photos/200?random=25",
        stock: 13,
    },
];